apiVersion: v1
kind: Service
metadata:
  name: {{ include "zhangyuan.name" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zhangyuan.name" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zhangyuan.name" . }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
  - port: {{ .Values.admin.port }}
    targetPort: {{ .Values.admin.port }}
