apiVersion: v1
kind: ConfigMap
metadata:
  name: zhangyuan-config
  namespace: zhangyuan
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "zhangyuan"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio-service:9000"
  NUXT_PUBLIC_API_BASE: "http://api-service:8080"
  JAVA_OPTS: "-Xms256m -Xmx768m"
  SPRING_PROFILES_ACTIVE: "prod"
