apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: zhangyuan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: zhangyuan-web:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: zhangyuan-config
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "512m"
            memory: "512Mi"
